### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by serkkz** [Moguri/blend2bam#31] opened 2020-05-09 15:21 UTC
I decided to use this tool for the first time.

```
D:\>D:\Panda3D-1.10.6-x64\python\Scripts\blend2bam.exe box.blend box.bam --blender-dir "D:\Program Files\Blender Foundation\Blender 2.82"
Blender version is 2.8+, forcing gltf28 pipeline
Blender 2.82 (sub 7) (hash 375c7dc4caf4 built 2020-03-12 15:41:08)
Read prefs: C:\Users\Serega\AppData\Roaming\Blender Foundation\Blender\2.82\config\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
found bundled python: D:\Program Files\Blender Foundation\Blender 2.82\2.82\python
srcroot: D:\
Exporting: ['D:\\box.blend']
Export to: C:\Users\Serega\AppData\Local\Temp
Read blend: D:\box.blend
Converting .blend file (D:\box.blend) to .gltf (C:\Users\Serega\AppData\Local\Tempbox.gltf)
Making particles on Camera real
Making particles on Cube real
Making particles on Light real
'D:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\site-packages\extern_draco.dll' exists, draco mesh compression is available
15:17:03 | INFO: Starting glTF 2.0 export
15:17:03 | INFO: Extracting primitive: Cube
15:17:03 | INFO: Primitives created: 1
15:17:03 | INFO: Finished glTF 2.0 export in 0.006448030471801758 s


Blender quit
Traceback (most recent call last):
  File "d:\panda3d-1.10.6-x64\python\lib\shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] Не удается найти указанный файл: 'C:\\Users\\Serega\\AppData\\Local\\Temp\\box.gltf' -> 'C:\\Users\\Serega\\AppData\\Local\\Temp\\tmph_kset5x'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\panda3d-1.10.6-x64\python\lib\site-packages\blend2bam\cli.py", line 96, in convert
    src2tmp.convert_single(srcfile, tmpfile.name)
  File "d:\panda3d-1.10.6-x64\python\lib\site-packages\blend2bam\blend2gltf\__init__.py", line 49, in convert_single
    shutil.move(dstout, dst)
  File "d:\panda3d-1.10.6-x64\python\lib\shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "d:\panda3d-1.10.6-x64\python\lib\shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "d:\panda3d-1.10.6-x64\python\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Serega\\AppData\\Local\\Temp\\box.gltf'
Failed to convert all file
```

**Comment by Moguri** [comment] 2020-05-22 01:31
Closing as a duplicate of #24

**Closed by Moguri** 2020-05-22 01:31 UTC
Labels: bug, duplicate
