### ISSUE TITLE
Textures not loading when loading .blend files, but glTF works

### ISSUE THREAD

**Issue by izzyboris** [Moguri/blend2bam#85] opened 2023-07-22 05:40 UTC
blend2bam: 0.21 (Python 3.11 pip)
Blender: 3.6.0, 3.3.9, 2.9 (tried all three with --blender-dir)
Panda3d: 1.10.13.post1

Textures added in Blender do not load or display in Panda3d or pview; model appears blank.

Import/conversion runs without logged errors. Defaults to Blender 3.3.9, but all three versions noted above have been tried with manual conversion to .bam. Also tried using '--texture embed' explicitly and other --texture options with no change.

However, exporting the same .blend model using Blender (all three versions) to .gltf/.glb first does display the texture properly in both Panda3d and pview.

To reproduce:
- Convert .blend sample model attached using blend2bam (`blend2bam 1x1base.blend 1x1base.bam`) and load in pview.exe - texture is blank. 
- Open .blend file in Blender and export to .glb, then load in pview.exe -- texture appears fine (see screenshot).

[1x1base.zip](https://github.com/Moguri/blend2bam/files/12135789/1x1base.zip)
![1x1base](https://github.com/Moguri/blend2bam/assets/137025642/2d6adbc6-19d4-466f-be26-604b3bddf79a)

**Comment by Moguri** [comment] 2023-07-22 15:53
I suspect this is actually a duplicate of #78.

**Comment by Moguri** [comment] 2023-07-26 18:14
Taking a closer look at this, the default `--textures ref` does not work with packed textures, which I suppose makes sense. However, when I use `--textures embed`, it works for me using `pview`.

**Comment by IzzyBoris** [comment] 2023-07-26 19:55
I confirmed that '--textures embed' does work and textures appear normally either when the .blend file either packs or references the original texture. However the textures don't load when using either 'copy' or 'ref', even with the .blend file using an unpacked texture, at least with Blender 3.6. Same behavior was seen both in a test driver program and also pview.

Tested this running blend2bam to pre-convert to .bam and load the .bam file explicitly.

Since 'ref' is the default texture mode, is there any way to default blend2bam to 'embed' mode when importing models on-the-fly at runtime?

**Comment by Moguri** [comment] 2023-07-27 05:35
`--textures copy` is also working for me, but only with a dev/master build of blend2bam.

There probably is a way to auto switch to embed when using ref on packed textures. However, I plan to switch the default to `copy` here soon since it works in more situations.

**Closed** 2023-09-25 03:34 UTC

**Comment by jez-moxmo** [comment] 2023-11-09 07:43
not sure if I can post in closed comments but I think blend2bam is where my issues stem. I am having a hard to applying textures to a rigged model. As soon as there are geoms, it seems like it's difficult to apply textures. I don't know if this is related to this issue or it's something with the bam2egg process. Either way it's giving me a migraine.

**Comment by Moguri** [comment] 2023-11-09 23:19
@jez-moxmo It's probably better to open a new issue and further explain the issue you are running into along with a way to reproduce the issue (ideally a blend file that shows the problem).
