### ISSUE TITLE
Crash on Blender 4.2

### ISSUE THREAD

**Issue by raytopianprojects** [Moguri/blend2bam#96] opened 2024-09-14 17:39 UTC
When I try and run blend2bam with blender 4.2 I get the following error.

PyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module.

File "C:\Users\user\PycharmProjects\TextWorld\VEN\lib\site-packages\blend2bam\blender_scripts\exportgltf.py", line 268, in convert_files  
    convertfn(settings, src, dst)
  File "C:\Users\user\PycharmProjects\TextWorld\VEN\lib\site-packages\blend2bam\blender_scripts\exportgltf.py", line 178, in export_gltf    
    from io_scene_gltf2.io.com.gltf2_io_debug import set_output_level #pylint: disable=import-error
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'set_output_level' from 'io_scene_gltf2.io.com.gltf2_io_debug' (C:\Users\user\Desktop\Games\Steam\steamapps\common\Blender\4.2\scripts\addons_core\io_scene_gltf2\io\com\gltf2_io_debug.py)
Failed to convert C:\Users\user\PycharmProjects\Engine\levels\island.blend to gltf
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\TextWorld\VEN\lib\site-packages\blend2bam\cli.py", line 59, in convert
    tmpfiles = src2tmp.convert(srcdir, tmpdir, files_to_convert)
  File "C:\Users\user\PycharmProjects\TextWorld\VEN\lib\site-packages\blend2bam\blend2gltf.py", line 25, in convert
    blenderutils.run_blender_script(self.script_file, args, blenderdir=blenderdir)
  File "C:\Users\user\PycharmProjects\TextWorld\VEN\lib\site-packages\blend2bam\blenderutils.py", line 35, in run_blender_script
    run_blender(
  File "C:\Users\user\PycharmProjects\TextWorld\VEN\lib\site-packages\blend2bam\blenderutils.py", line 27, in run_blender
    subprocess.check_call(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)

**Comment by Moguri** [comment] 2024-10-13 22:47
Duplicate of #94

**Closed by Moguri** 2024-10-13 22:47 UTC
